version: '3.9'

services:
  # MySQL
  database:
    container_name: postgres_13
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_database
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data/:rw
      - ./test_dump.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  postgres:
