- hosts: mysql
  gather_facts: True
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - install_mysql
  
  environment:
     http_proxy: http://netology.space:8118
     https_proxy: http://netology.space:8118